apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-catalogue
  namespace: pss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pss-local-retain
  resources:
    requests:
      storage: 1Gi
